### ISSUE TITLE
Unity 4.5 doesn't work with OpenVR

### ISSUE THREAD

**Issue by hampa** [i-saint/Unity5Effects#2]
The Raymarcher stopped working in Unity 5.4 with OpenVR.

The left and right eye are rendering differently. It works on Oculus but not Vive.

Could be related to this unity 5.4 release note:
Note that native OpenVR support renders with an off-center asymmetric projection matrix. This means that any shaders which relied on fov / aspect may not work correctly.

**Comment by hampa** [comment]
The raymarcher still has convergence problems with SteamVR.

Could it be a similar problem like kode80 had in this link?
https://forum.unity3d.com/threads/unity-5-4-steamvr-fullscreen-quad-convergence-bug.407798/

**Comment by i-saint** [comment]
I have no test environment for this issue.

**Comment by friken** [comment]
I see this issue is closed but I'm curious if a solution was found. This is still an issue for for vive/openvr
